### ISSUE TITLE
Library import - problem

### ISSUE THREAD

**Issue by Tommi88** [timokorkalainen/Unity-GeoJSONObject#2]
Hello Timo,

I faced a problem with importing this library into Unity. Can you advice me what I am doing wrong.
I tested it many times, changed file locations etc. Nothing worked for me.
Do you know how can I import this library to Unity?
I was thinking that only I have to do is to move it to the Asset folder.

![image](https://user-images.githubusercontent.com/32575360/31285416-21a86886-aab3-11e7-9dbf-c282bd8c5aef.png)

Regards,
Tomasz

You can contact me via email as well:
tomasz.zawadzki@mu.ie

**Comment by timokorkalainen** [comment]
Hi,

Just download and import this library into your Assets folder and it should start working: https://github.com/mtschoen/JSONObject

Regards,
Timo

**Comment by Tommi88** [comment]
Thanks Timo,


Kind regards,

--
Tomasz ZAWADZKI | Ph.D. |

Senior Postdoctoral Researcher
| Profile<https://www.maynoothuniversity.ie/people/tomasz-zawadzki> | Building City Dashboards - Project Website<http://dashboards.maynoothuniversity.ie/> |
National Centre for Geocomputation | Maynooth University |
----------------------------------------------------------------------------
Editorial Board Member | AIRCCSE<http://airccse.org/journal/ijcga/editor.html> |
| International Journal of Computer Graphics & Animation |
----------------------------------------------------------------------------
Personal website | WEBISTE<https://tomasz-zawadzki.wixsite.com/home> |
----------------------------------------------------------------------------
